version: '3.8'

services:
  jupyter:
    image: jupyter/base-notebook:python-3.9
    container_name: pandas_jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
